### ISSUE TITLE
tooltip "click to edit" not changing text?

### ISSUE THREAD

**Issue by ecl1pse** [nathanvda/on_the_spot#49]
I changed tooltip to "Edit" in on_the_spot.en.yml but it's not changing text. I restarted server. Any suggestions?

```
en:
  on_the_spot:
    ok: Ok
    cancel: Cancel
    tooltip: Edit
    access_not_allowed: Access is not allowed
```
